version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ulearner-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: potgress
      POSTGRES_PASSWORD: 29082006
      POSTGRES_DB: ulearner
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U potgress -d ulearner']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
