spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db}:${DB_PORT:5432}/ulearner_prod
    username: ${DB_USERNAME:ulearner}
    password: ${DB_PASSWORD:securePassword}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
  file:
    name: logs/ulearner-prod.log

server:
  port: 8080
